(require 'package)
(add-to-list 'package-archives
	     '("melpa" . "http://melpa.org/packages/") t)
(when (< emacs-major-version 24)
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize)
(require 'evil)
(evil-mode 1)
(require 'evil-surround)
(global-evil-surround-mode 1)
(evilnc-default-hotkeys)
(require 'emmet-mode)
(global-evil-leader-mode)
(evil-leader/set-key "," 'find-file)
(require 'autopair)
(autopair-global-mode)
