(tool-bar-mode 0)
(menu-bar-mode 0)
(scroll-bar-mode 0)
(setq visible-bell nil)
(setq initial-scratch-message "")
(setq inhibit-startup-message t)
(setq ring-bell-function 'ignore)
;; (setq mode-line-format nil)
;; (setq-default mode-line-format nil) 
(set-fringe-mode 0)
(setq make-backup-files nil)
(set-fringe-mode 0)
(setq linum-format "%d ")
(show-paren-mode 1)
